import os


S3_BUCKET = os.environ.get("S3_BUCKET_NAME", "").strip()

TARGET_WIDTH = 1080
TARGET_HEIGHT = 1920

DEFAULT_LAYOUT = "full"
DEFAULT_BAIT_VIDEO = "minecraft_night"
GAMEPLAY_S3_PREFIX = os.environ.get("GAMEPLAY_S3_PREFIX", "gameplay")

COLUMBIA_CWD = "/asd"
COLUMBIA_MODEL_PATH = "weight/finetuning_TalkSet.model"

COOKIE_PATH = "/root/cookies.txt"

MAX_CLIP_WORKERS = 2

WHISPERX_MODEL_SIZE = "large-v2"
WHISPERX_DEVICE = "cuda"
WHISPERX_COMPUTE_TYPE = "float16"
WHISPERX_BATCH_SIZE = 16

DEFAULT_CLIP_DURATION = 60.0
BAIT_MARGIN_SECONDS = 5.0

SUBTITLE_MAX_WORDS = 5
SUBTITLE_FONT_NAME = "Montserrat"
SUBTITLE_FONT_SIZE = 100
SUBTITLE_MARGIN_V = 480
SUBTITLE_MARGIN_LR = 50
